name: ChatGPT Integration

on: [push]  # Event that triggers the workflow, such as a push to the repository

jobs:
  chatgpt:
    runs-on: ubuntu-latest    # The operating system to run the workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository's code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have any dependencies

      - name: Run ChatGPT script
        run: python /home/ec2-user/chatpycode.py  # Replace with your ChatGPT script path
