name: Create S3 Bucket

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'Name of the S3 bucket'
        required: true

jobs:
  create_s3_bucket:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Create S3 bucket
      id: create_bucket
      run: |
        arn=$(aws s3api create-bucket --bucket ${{ github.event.inputs.bucket_name }} --region eu-central-1 --create-bucket-configuration LocationConstraint=eu-central-1 --query 'BucketArn' --output text)
        name=${{ github.event.inputs.bucket_name }}
        echo "::set-output name=arn::$arn"
        echo "::set-output name=name::$name"

    - name: Display bucket ARN and name
      run: |
        echo "Bucket ARN: ${{ steps.create_bucket.outputs.arn }}"
        echo "Bucket Name: ${{ steps.create_bucket.outputs.name }}"
