name: Bucket Action second

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'Bucket Name'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Bucket Name
        run:  echo "Bucket Name:${{ github.event.inputs.bucket_name }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Create S3 Bucket
        run: |
          aws s3api create-bucket --bucket ${{ github.event.inputs.bucket_name }} --region eu-central-1 --create-bucket-configuration LocationConstraint=eu-central-1
          aws s3api wait bucket-exists --bucket ${{ github.event.inputs.bucket_name }}
          
