name: Create S3 Bucket

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'Bucket Name'
        required: true

jobs:
  create_bucket:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Display Bucket Name
        run:  echo "Bucket Name:${{ github.event.inputs.bucket_name }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Create S3 bucket
        id: create_bucket
        run: |
         aws s3api create-bucket --bucket ${{ github.event.inputs.bucket_name }} --region eu-central-1 --create-bucket-configuration LocationConstraint=eu-central-1 > bucket_info.txt
         echo "::set-output name=arn::$(grep -oP '(?<=\"Location\": \").*?(?=\")' bucket_info.txt)"
         echo "::set-output name=name::${{ github.event.inputs.bucket_name }}"

      - name: Display bucket ARN and name
        run: |
          echo "Bucket ARN: ${{ steps.create_bucket.outputs.arn }}"
          echo "Bucket Name: ${{ steps.create_bucket.outputs.name }}"
          
                
      - name: Getting s3 details
        id: push_bucket_details
        run: |
          echo "BUCKET_NAME= $bucket_name" > $GITHUB_WORKSPACE/bucket-info.txt
          echo "BUCKET_ARN= $bucket_arn" >> $GITHUB_WORKSPACE/bucket-info.txt


      - name: Upload bucket-info artifact
        uses: actions/upload-artifact@v2
        with:
          name: bucket-details
          path: bucket-details.txt

        
