name: Create S3 Bucket

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-s3-bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check if S3 Bucket exists
        id: s3-bucket-exists
        run: |
          aws s3api head-bucket --bucket ${{ github.event.inputs.bucket_name }} 2>&1
          if [[ $? -eq 0 ]]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Create S3 Bucket
        run: |
          bucket_exists=${{ steps.s3-bucket-exists.outputs.exists }}
          if [[ $bucket_exists == "false" ]]; then
            aws s3api create-bucket \
              --bucket ${{ github.event.inputs.bucket_name }} \
              --region eu-central-1 \
              --create-bucket-configuration LocationConstraint=eu-central-1
          else
            echo "Error: S3 Bucket already exists."
            exit 1
          fi

      - name: Display S3 Bucket ARN
        run: |
          aws s3api get-bucket-location \
            --bucket ${{ github.event.inputs.bucket_name }} \
            --query "LocationConstraint" \
            --output text
