name: ChatGPT Integration

on: [push]  # Event that triggers the workflow, such as a push to the repository

jobs:
  chatgpt:
    runs-on: ubuntu-latest    # The operating system to run the workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository's code

      - name: Run ChatGPT script
        run: python /home/ec2-user/chatpycode.py  # Replace with your ChatGPT script path
